export const END_POINT = {
    LOAD_DIVISION_LIST: 'LOAD_DIVISION_LIST',
    GET_DIVISION_DEPTH: 'GET_DIVISION_DEPTH',
    ADD_DIVISION: 'ADD_DIVISION',
    DELTE_DIVISION: 'DELTE_DIVISION',
    GET_ENTITY_LIST: 'GET_ENTITY_LIST',
    ADD_ENTITY: 'ADD_ENTITY',
    GET_ENTITY: 'GET_ENTITY',
    DELTE_ENTITY: 'DELTE_ENTITY',
}