export const END_POINT = {
    LOAD_DIVISION_LIST: 'LOAD_DIVISION_LIST',
    LOAD_DIVISION_ROOT: 'LOAD_DIVISION_ROOT',
    LOAD_DIVISION_LEVEL: 'LOAD_DIVISION_LEVEL',
    ADD_DIVISION: 'ADD_DIVISION',
    DELTE_DIVISION: 'DELTE_DIVISION',
    ADD_ENTITY: 'ADD_ENTITY',
    GET_ENTITY: 'GET_ENTITY',
    DELTE_ENTITY: 'DELTE_ENTITY',
}